name: Run integration scripts

on: push

jobs:
  test:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.allowed_failure }}

    strategy:
      fail-fast: false
      matrix:
        php: [ '5.6', '7.0', '7.1', '7.2', '7.3', '7.4', '8.0' ]
        allowed_failure: [ false ]
        include:
          # PHP nightly.
          - php: '8.1'
            allowed_failure: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP ${{ matrix.php }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: pcov
          # https://make.wordpress.org/hosting/handbook/handbook/server-environment/#php-extensions
          extensions: curl, dom, exif, fileinfo, hash, json, mbstring, mysqli, libsodium, openssl, pcre, imagick, xml, zip

      - name: Install Composer dependencies (PHP < 8.0 )
        if: ${{ matrix.php < 8.0 }}
        uses: ramsey/composer-install@v1

      - name: Install Composer dependencies (PHP >= 8.0)
        if: ${{ matrix.php >= 8.0 }}
        uses: ramsey/composer-install@v1
        with:
          composer-options: --ignore-platform-reqs

      - name: Show version info
        run: |
          php --version
          ./vendor/bin/psalm --version
          ./vendor/bin/phpcs --version
          ./vendor/bin/phpcbf --version
          ./vendor/bin/phplint --version

      - name: Run PHP_CodeSniffer
        run: composer cs

      - name: Run PHPLint
        run: composer lint

      - name: Run Psalm
        run: composer psalm
